/*
 * Copyright © 2010 Intellectual Reserve, Inc. All Rights reserved.
 */
package org.familysearch.gal.shared.rest.exception;

import javax.ws.rs.core.Response.Status;

/**
 * Represents an invalid request, HTTP response code of 400. This
 * could be generated by a POST or PUT operation if there is missing
 * or invalid data.
 */
public class BadRequestException extends ServiceRESTException {

    private static final long serialVersionUID = -7743599185936171767L;

    {
        super.statusType(Status.BAD_REQUEST);
    }

    public BadRequestException() {
    }

    public BadRequestException(String message) {
        super(message);
    }

    public BadRequestException(Throwable cause) {
        super(cause);
    }

    public BadRequestException(String message, Throwable cause) {
        super(message, cause);
    }

}
