/*
 * Copyright © 2010 Intellectual Reserve, Inc. All Rights reserved.
 */
package org.familysearch.gal.shared.rest.exception;

import javax.ws.rs.core.Response.Status;

/**
 * Represents a constraint-error, HTTP response code of 409.
 * This could be generated by a POST or PUT operation that
 * can't be processed because it would violate a model or
 * database constraint.
 *
 */
public class ConstraintException extends ServiceRESTException {

    private static final long serialVersionUID = 3827464184732577340L;
    {
        super.statusType(Status.CONFLICT);
    }

    public ConstraintException() {
    }

    public ConstraintException(String message) {
        super(message);
    }

    public ConstraintException(Throwable cause) {
        super(cause);
    }

    public ConstraintException(String message, Throwable cause) {
        super(message, cause);
    }

}
